### ISSUE TITLE
Incompatibility with DashLoader

### ISSUE THREAD

**Issue by buranyaa** [TheWinABagel/Zenith#141] opened 2024-04-07 14:18 UTC
Crashes on startup
Version: 1.20.1
Zenith Version: 1.1.7-1.20.1
Mods: Zenith (and dependencies, attributes and fakerlib), DashLoader, and Fabric api
MC Log: https://mclo.gs/JJd01jX

**Comment by muon-rw** [comment] 2024-04-09 17:34
DashLoader has many other compatibility issues and is no longer being developed, I would personally just recommend removing it. 

Edit: Case in point (actually the cause here), and marked as wontfix by Porting Lib:

https://github.com/Fabricators-of-Create/Porting-Lib/issues/73
https://github.com/Fabricators-of-Create/Create/issues/1412

**Comment by TheWinABagel** [comment] 2024-04-16 18:38
Yeah, won't add compat for a discontinued mod.

**Closed as not planned by TheWinABagel** 2024-04-16 18:38 UTC
