### ISSUE TITLE
1.19.2 Server Crash

### ISSUE THREAD

**Issue by witchoyy** [TheWinABagel/Zenith#20] opened 2023-04-27 19:09 UTC
[main/ERROR]: Failed to start the minecraft server
--
788 | java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'zenith'!
789 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.19.jar:?]
790 | at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.19.jar:?]
791 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.19.jar:?]
792 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.19.jar:?]
793 | at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.19.jar:?]
794 | at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
795 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.19.jar:?]
796 | at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.19.jar:?]
797 | at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.19.jar:?]
798 | at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.19.jar:?]
799 | Caused by: java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.item.v1.ItemTooltipCallback in environment type SERVER
800 | at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.14.19.jar:?]
801 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.14.19.jar:?]
802 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.14.19.jar:?]
803 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.19.jar:?]
804 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.19.jar:?]
805 | at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
806 | at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
807 | at safro.zenith.spawn.SpawnerModule.init(SpawnerModule.java:63) ~[zenith-0.5.6+1.19.2.jar:?]
808 | at safro.zenith.Zenith.onInitialize(Zenith.java:98) ~[zenith-0.5.6+1.19.2.jar:?]
809 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.19.jar:?]
810 | ... 7 more

**Comment by TheWinABagel** [comment] 2023-04-27 20:12
Duplicate of #19

**Closed by TheWinABagel** 2023-04-27 20:12 UTC
