### ISSUE TITLE
Zenith not working with latest Fabric API (1.20.1)

### ISSUE THREAD

**Issue by gamerpotion** [TheWinABagel/Zenith#151] opened 2024-04-29 22:33 UTC
Please see below. Zenith 1.20.1 latest Fabric version not compatible with latest Fabric API.

```
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Fabric API' (fabric-api) 0.92.1+1.20.1 with mod 'Fabric API' (fabric-api), version 0.92.0+1.20.1.
More details:
	 - Mod 'Zenith' (zenith) 1.1.7-1.20.1 requires version 0.92.0+1.20.1 of mod 'Fabric API' (fabric-api), but only the wrong version is present: 0.92.1+1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by muon-rw** [comment] 2024-05-03 18:03
Duplicate of #145

**Closed as completed** 2024-05-04 00:22 UTC
